// let's imagine this file is autogenerated from the backend
// ideally, we want to keep these api related types in sync
// with the backend instead of manually writing them out

import type { AuthProvidersEnum, RoleEnum, StatusEnum } from 'src/config/enum';

export type BaseEntity = {
  id: string;
  createdAt: number;
};

export type Entity<T> = {
  [K in keyof T]: T[K];
} & BaseEntity;

export type Meta = {
  page: number;
  total: number;
  totalPages: number;
};

export type User = Entity<{
  firstName: string;
  lastName: string;
  email: string;
  username: string;
  password?: string;
  bio?: string;
  avatar?: FileResponse;
  provider: AuthProvidersEnum;
  role?: {
    id: RoleEnum;
    name: string;
  };
  status?: {
    id: StatusEnum;
    name: string;
  };
  createdAt: Date;
  updatedAt: Date;
  deletedAt?: Date;
}>;

export type Post = Entity<{
  title: string;
  description?: string;
  content: string;
  banner?: FileResponse;
  tags?: string[];
}>;

export type AuthResponse = {
  user: User;
};

export type FileResponse = {
  id: string;
  path: string;
};
